enum state_t{GOING_UP, GOING_DOWN, STOP_GOING_UP, STOP_GOING_DOWN, IDLE, EMERGENCY, BOOT};
enum event_t{GO_UP, GO_DOWN, STOP, EMERGENCY_BUTTON, OBSTRUCTION};
enum speed_t{S_UP, S_DOWN, S_STOP};
enum button_t{B_UP, B_DOWN, B_ELEVATOR};